package dms

type RouterGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.

	DocumentAgenciesRouter
	DocumentCategoriesRouter
	DocumentFieldReferencesRouter
	DocumentFieldsRouter
	DocumentFilesRouter
	DocumentPriorityLevelsRouter
	DocumentRelationReferencesRouter
	DocumentSignerReferencesRouter
	DocumentsRouter
	DocumentUsersRouter
	DocumentRulesRouter
	DocumentSignersRouter
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.

	GoogleOAuthRouter
}
