package dms

type ServiceGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.

	DocumentAgenciesService
	DocumentCategoriesService
	DocumentFieldReferencesService
	DocumentFieldsService
	DocumentFilesService
	DocumentPriorityLevelsService
	DocumentRelationReferencesService
	DocumentSignerReferencesService
	DocumentsService
	DocumentUsersService
	DocumentRulesService
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
