package dms

type ApiGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.

	DocumentAgenciesApi
	DocumentCategoriesApi
	DocumentFieldReferencesApi
	DocumentFieldsApi
	DocumentFilesApi
	DocumentPriorityLevelsApi
	DocumentRelationReferencesApi
	DocumentSignerReferencesApi
	DocumentsApi
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
